import { Experience } from "~/types";

export default defineEventHandler(
  (): Array<Experience> => [
    {
      title: "Sr. Engineer, Full Stack",
      company: "Slickdeals",
      location: "Remote",
      dates: "2021 - 2023",
      items: [
        "Refactored, expanded, and modularized the browser extension involving Vite, Vue, Storybook, Typescript, and SASS",
        "Collaborated with the product team on 50+ Figma designs and 30+ A/B Tests",
        "Developed REST API controllers, services, repositories, and data models in PHP",
        "Helped improve enterprise-level microservices and monolithic Git repos",
        "Integrated code with Google Tag Manager, Google Analytics, and Sentry",
        "Established and maintained 100+ unit tests and functional tests",
        "Contributed to Agile Scrum and Kanban teams by assisting in weekly sprint planning and refinement, quarterly planning with OKRs and KPIs",
        "Defined and completed implementation and test plans for 200+ tickets in JIRA",
        "Performend code reviews and mentored junior developers",
      ],
      links: [
        {
          name: "Slickdeals",
          link: "https://slickdeals.net/",
        },
        {
          name: "Slickdeals Browser Extension",
          link: "https://slickdeals.net/extension/",
        },
      ],
      skills: [
        "Vue",
        "SCSS",
        "TypeScript",
        "REST API",
        "PHP",
        "PHPUnit",
        "Symfony",
        "MySQL",
        "Docker",
        "Vitest",
        "Git",
        "Google Tag Manager",
      ],
    },
    {
      title: "Lead Full Stack Engineer",
      company: "Smart Software Solutions",
      location: "Hybrid - Las Vegas, NV",
      dates: "2016 - 2021",
      items: [
        "Developed responsive web and hybrid mobile applications following Material Design in Angular",
        "Developed REST API controllers, repositories, services, and data models in Typescript with Node.js, Express, Sequelize and MySQL",
        "Designed database schemas and performed SQL query optimization",
        "Created and proposed project estimates to clients over web and email",
        "Trained new hires and delegated tasks to developers across multiple projects",
      ],
      skills: [
        "Angular",
        "Ionic",
        "Material Design",
        "PHP",
        "Drupal",
        "Google Firebase",
        "AWS Route53",
        "AWS EC2",
        "WordPress",
        "Node.js",
        "Express",
        "MariaDB",
        "Linux",
      ],
    },
    {
      title: "Full Stack Engineer",
      company: "Smart Software Solutions",
      location: "Las Vegas, NV",
      dates: "2014 - 2016",
      items: [
        "Developed progressive web applications following Material Design with Ionic and Angular",
        "Developed REST API controllers, repositories, services, and data models in Typescript with Node.js, Express, Sequelize and MariaDB",
      ],
      skills: [
        "Angular",
        "Ionic",
        "Material Design",
        "PHP",
        "Drupal",
        "WordPress",
        "Node.js",
        "Express",
        "Sequelize",
        "MariaDB",
        "Java",
        "Linux",
      ],
    },
  ],
);
